### ISSUE TITLE
Resetting singleton instance

### ISSUE THREAD

**Issue by ThomDietrich** [mammo0/py-simple-singleton#4]
Hey there,
maybe this is too obvious 🙃 how would one go about resetting the singleton instance? A singleton has its use but sometimes you just want to start with a fresh instance...

Thanks!

**Comment by TonyDiana** [comment]
If the class is singleton, all its instantiated objects will be the same, it is unavoidable.

If you want an object that sometimes is and sometimes is not, something strange is the truth:

class foo (object):
a lot of work

class Single (foo, metaclass = Singleton):
     pass

**Comment by mammo0** [comment]
Hello,

at first I must agree with @TonyDiana. The resetting of a singleton is not that thing it is intended for...

But as with the most things in the Python world there's a "hacky" way of resetting the singleton:
If you use the
- `Singleton` metaclass, your Singleton class will have a `_instance` variable that can be set to `None`.
- `SingletonArgs` metaclass, your Singleton class will have a `_instances` variable that can be set to `{}`.

**Important:** I just changed the variable naming. So the described workaround will only work on version `>=1.2.1`.

You can have a look at this example:
```python
from simple_singleton import Singleton, SingletonArgs


class Foo(metaclass=Singleton):
    pass


f = Foo()
f2 = Foo()

assert f == f2

Foo._instance = None
f = Foo()

assert f != f2


class Bar(metaclass=SingletonArgs):
    pass


b = Bar()
b2 = Bar()

assert b == b2

Bar._instances = {}
b = Bar()

assert b != b2
```

**Comment by mammo0** [comment]
@ThomDietrich: I'm closing this now.

If there are any more questions/problems, please feel free to reopen this issue.

**Comment by ThomDietrich** [comment]
@mammo0 sorry for the late response. Your response is exactly what I was asking for. Thanks.

And yes, I totally agree with your arguments. The project I am working on has a clear use case for the singleton pattern for its main structure and logic. A rare function is to restart the logic though. For this we could explicitly reset all data members of the singleton class, or replace the unique instance. I prefer the latter :)
Thanks!
